package dev.ledgerbank.gateway;
import java.security.SecureRandom;import java.time.Duration;import java.util.*;import java.util.concurrent.ConcurrentHashMap;import org.springframework.beans.factory.annotation.Value;import org.springframework.core.Ordered;import org.springframework.http.*;import org.springframework.http.server.reactive.ServerHttpRequest;import org.springframework.stereotype.Component;import org.springframework.web.server.*;import reactor.core.publisher.Mono;
@Component class EdgeFilter implements WebFilter,Ordered{
 private final Set<String>origins;private final boolean secure;private final SecureRandom random=new SecureRandom();private final Map<String,Attempts>loginAttempts=new ConcurrentHashMap<>();
 EdgeFilter(@Value("${ledgerbank.allowed-origins}")String origins,@Value("${ledgerbank.cookie-secure}")boolean secure){this.origins=Set.of(origins.split(","));this.secure=secure;}
 @Override public int getOrder(){return -1;}
 @Override public Mono<Void>filter(ServerWebExchange exchange,WebFilterChain chain){ServerHttpRequest request=exchange.getRequest();String method=request.getMethod().name(),path=request.getPath().value();String origin=request.getHeaders().getOrigin();if(origin!=null&&!origins.contains(origin)){exchange.getResponse().setStatusCode(HttpStatus.FORBIDDEN);return exchange.getResponse().setComplete();}
  if(path.equals("/api/v1/auth/login")&&!allowLogin(request.getRemoteAddress()==null?"unknown":request.getRemoteAddress().getAddress().getHostAddress())){exchange.getResponse().setStatusCode(HttpStatus.TOO_MANY_REQUESTS);return exchange.getResponse().setComplete();}
  HttpCookie csrf=request.getCookies().getFirst("XSRF-TOKEN");if(Set.of("POST","PUT","PATCH","DELETE").contains(method)){String header=request.getHeaders().getFirst("X-XSRF-TOKEN");if(csrf==null||header==null||!java.security.MessageDigest.isEqual(csrf.getValue().getBytes(),header.getBytes())){exchange.getResponse().setStatusCode(HttpStatus.FORBIDDEN);return exchange.getResponse().setComplete();}}
  if(csrf==null){byte[]b=new byte[24];random.nextBytes(b);exchange.getResponse().addCookie(ResponseCookie.from("XSRF-TOKEN",Base64.getUrlEncoder().withoutPadding().encodeToString(b)).httpOnly(false).secure(secure).sameSite("Lax").path("/").maxAge(Duration.ofHours(8)).build());}
  ServerHttpRequest.Builder forwarded=request.mutate();forwarded.headers(h->h.remove(HttpHeaders.AUTHORIZATION));HttpCookie access=request.getCookies().getFirst("LB_ACCESS");if(access!=null)forwarded.header(HttpHeaders.AUTHORIZATION,"Bearer "+access.getValue());String cid=Optional.ofNullable(request.getHeaders().getFirst("X-Correlation-ID")).orElseGet(()->UUID.randomUUID().toString());forwarded.headers(h->h.set("X-Correlation-ID",cid));exchange.getResponse().getHeaders().set("X-Correlation-ID",cid);return chain.filter(exchange.mutate().request(forwarded.build()).build());}
 private boolean allowLogin(String key){long now=System.currentTimeMillis();Attempts a=loginAttempts.compute(key,(k,v)->v==null||now-v.windowStart>60000?new Attempts(now,1):new Attempts(v.windowStart,v.count+1));return a.count<=10;}record Attempts(long windowStart,int count){}
}
